import jsPDF from 'jspdf'

const NAVY  = [26, 58, 92]
const GRAY  = [107, 114, 128]
const LGRAY = [200, 210, 220]
const WHITE = [255, 255, 255]

function hex(r, g, b) { return [r, g, b] }

export function exportQuotePDF({ project, rooms, trades, total }) {
  const doc  = new jsPDF({ unit: 'mm', format: 'a4' })
  const pw   = 210
  const mg   = 20
  const cw   = pw - mg * 2
  let y      = 0

  // ── header bar
  doc.setFillColor(...NAVY)
  doc.rect(0, 0, pw, 42, 'F')

  doc.setTextColor(...WHITE)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.text('BuildFlow Pro', mg, 18)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(160, 195, 230)
  doc.text('PROJECT QUOTE & ESTIMATE', mg, 27)

  // date + ref top-right
  const today = new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })
  doc.setTextColor(160, 195, 230)
  doc.setFontSize(8)
  doc.text(today, pw - mg, 18, { align: 'right' })
  doc.text(`Ref: BFP-${Date.now().toString().slice(-6)}`, pw - mg, 25, { align: 'right' })

  y = 56

  // ── project info
  doc.setTextColor(...NAVY)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(15)
  doc.text(project.client_name || 'Client', mg, y)

  y += 7
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(...GRAY)
  if (project.address) doc.text(project.address, mg, y), y += 5
  doc.text(`Status: ${project.status || 'In Progress'}`, mg, y)
  if (project.notes) {
    y += 5
    doc.text(`Notes: ${project.notes}`, mg, y, { maxWidth: cw })
  }

  y += 10
  doc.setDrawColor(225, 230, 238)
  doc.setLineWidth(0.3)
  doc.line(mg, y, pw - mg, y)
  y += 10

  // ── rooms table
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...NAVY)
  doc.text('FLOOR PLAN BREAKDOWN', mg, y)
  y += 7

  // column headers
  doc.setFillColor(245, 247, 250)
  doc.rect(mg, y - 4, cw, 8, 'F')
  doc.setFontSize(7.5)
  doc.setTextColor(...GRAY)
  doc.text('ROOM',       mg + 2,         y + 1)
  doc.text('DIMENSIONS', mg + 58,        y + 1)
  doc.text('AREA',       mg + 100,       y + 1)
  doc.text('ESTIMATE',   pw - mg - 2,    y + 1, { align: 'right' })
  y += 9

  let roomTotal = 0
  rooms.forEach((r, i) => {
    if (i % 2 === 1) {
      doc.setFillColor(250, 251, 252)
      doc.rect(mg, y - 3.5, cw, 7.5, 'F')
    }
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...NAVY)
    doc.text(r.type, mg + 2, y + 1)
    doc.setTextColor(...GRAY)
    doc.text(`${r.wM}m × ${r.hM}m`, mg + 58, y + 1)
    doc.text(`${r.sqm} m²`, mg + 100, y + 1)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...NAVY)
    doc.text(`$${Math.round(r.cost).toLocaleString('en-AU')}`, pw - mg - 2, y + 1, { align: 'right' })
    roomTotal += r.cost
    y += 7.5

    if (y > 255) {
      doc.addPage()
      y = 20
    }
  })

  // rooms subtotal
  doc.setDrawColor(225, 230, 238)
  doc.line(mg, y + 2, pw - mg, y + 2)
  y += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(...NAVY)
  doc.text('Rooms subtotal', mg + 2, y + 1)
  doc.text(`$${Math.round(roomTotal).toLocaleString('en-AU')}`, pw - mg - 2, y + 1, { align: 'right' })
  y += 10

  doc.line(mg, y, pw - mg, y)
  y += 10

  // ── trade breakdown
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...NAVY)
  doc.text('COST BY TRADE', mg, y)
  y += 8

  const colW = (cw - 8) / 2
  trades.forEach((t, i) => {
    const col = i % 2
    const row = Math.floor(i / 2)
    const tx  = mg + col * (colW + 8)
    const ty  = y + row * 8

    doc.setFillColor(245, 247, 250)
    doc.rect(tx, ty - 3.5, colW, 7, 'F')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    doc.setTextColor(...GRAY)
    doc.text(t.name, tx + 2, ty + 1)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...NAVY)
    doc.text(`$${Math.round(t.amount).toLocaleString('en-AU')}`, tx + colW - 2, ty + 1, { align: 'right' })
  })
  y += Math.ceil(trades.length / 2) * 8 + 10

  // ── total bar
  doc.setFillColor(...NAVY)
  doc.rect(mg, y, cw, 18, 'F')
  doc.setTextColor(...WHITE)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text('TOTAL PROJECT ESTIMATE', mg + 4, y + 11)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(15)
  doc.text(`$${Math.round(total).toLocaleString('en-AU')}`, pw - mg - 4, y + 12, { align: 'right' })
  y += 28

  // ── footer
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  doc.setTextColor(...LGRAY)
  doc.text(
    'This estimate is valid for 30 days. Final costs may vary based on site conditions, material selection, and council requirements.',
    mg, y, { maxWidth: cw }
  )
  y += 9
  doc.setTextColor(160, 175, 190)
  doc.text('Generated by BuildFlow Pro', mg, y)
  doc.text(today, pw - mg, y, { align: 'right' })

  const filename = `${(project.client_name || 'quote').replace(/[^a-z0-9]/gi, '-')}-quote.pdf`
  doc.save(filename)
}
